### ISSUE TITLE
bad snmpwalk kills server

### ISSUE THREAD

**Issue by bhammond-internap** [joyent/node-snmpjs#238]
While working on a small server, I ran this: snmpwalk -v 2c -c oops 172.13.13.172 1.2.3.4 

Which threw an exception that killed the server:

/tmp/node_modules/snmpjs/lib/protocol/data.js:99
                throw new RangeError('object identifier is too short');
                ^
RangeError: object identifier is too short
    at Object.canonicalizeOID (/tmp/node_modules/snmpjs/lib/protocol/data.js:99:9)
    at oid_is_descended (/tmp/node_modules/snmpjs/lib/mib.js:69:20)
    at MIBNode.isAncestor (/tmp/node_modules/snmpjs/lib/mib.js:89:10)
    at new ProviderRequest (/tmp/node_modules/snmpjs/lib/provider.js:37:19)
    at /tmp/node_modules/snmpjs/lib/agent.js:183:13
    at Array.forEach (native)
    at Agent._do_getset (/tmp/node_modules/snmpjs/lib/agent.js:181:19)
    at Agent._process_req (/tmp/node_modules/snmpjs/lib/agent.js:408:8)
    at Agent._recv (/tmp/node_modules/snmpjs/lib/agent.js:450:7)
    at Socket._recv_binder (/tmp/node_modules/snmpjs/lib/agent.js:481:8)

Might be better to it invoke an error callback or something...

**Comment by BrkDalkiran** [comment]
I have the same problem. "object identifier" errors: "too short", "Object.canonicalizeOID", "exceeds encoding limit" etc.

Oid validation necessary for me since i have oid addresses assigned by end users.
