### ISSUE TITLE
Can't send empty string

### ISSUE THREAD

**Issue by dsalnikov** [joyent/node-snmpjs#245]
Hi, I am trying to send trap with empty string with such code:

```
var vb = [];
vb.push(snmp.varbind.createVarbind({
        // sysDescr.0
        oid: "1.3.6.1.4.1.2011.6.164.1.1.1.5.0",
        data: snmp.data.createData({
            type: "OctetString",
            value: ""
        })
    })
);
client.inform(ip, community, uptime, oid, vb, function(snmpmsg) {});
```

But snmjs crushes. 
Here is back trace:

```
assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: 0 == true
    at Writer._ensure (/usr/lib/node_modules/snmpjs/node_modules/asn1/lib/ber/writer.js:297:10)
    at Writer.writeBuffer (/usr/lib/node_modules/snmpjs/node_modules/asn1/lib/ber/writer.js:156:8)
    at SnmpOctetString._octetstring_encode [as encode] (/usr/lib/node_modules/snmpjs/lib/protocol/data.js:258:9)
    at SnmpVarbind.encode (/usr/lib/node_modules/snmpjs/lib/protocol/varbind.js:78:13)
    at SnmpStdPDU.encode (/usr/lib/node_modules/snmpjs/lib/protocol/pdu.js:240:21)
    at SnmpMessage.encode (/usr/lib/node_modules/snmpjs/lib/protocol/message.js:129:12)
    at send (/usr/lib/node_modules/snmpjs/lib/client.js:46:6)
    at Client.SNMPv2_Trap.Client.inform (/usr/lib/node_modules/snmpjs/lib/client.js:179:2)
    at /opt/snmpserv.js:108:16
    at Array.forEach (native)
```

**Comment by madwax** [comment]
Got around the problem by editing node-asn1.  I have no idea if its value to send empty strings in asn1 but I just removed the assert
